[package]
cairo-version = "2.5.4"
name = "chess"
version = "0.6.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply && ./scripts/default_auth.sh"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/chess/katana"
# Default account for katana with seed = 0
account_address = "0x5250ca23605451bbbd9d2ea1a5ccc6c4b420158ec0f3fed5ce218d4935a39eb"
private_key = "0x41a79ff14d3e147d54ed5f03ccdd5fcee8aca44576ba55e4ab7752ea239b631"
world_address = "0x1f47786624f9f6400f182246410d27a6e83d3e3ae3e6b7b40866d61717aa2b9" # Update this line with your world address


